# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
normalize_comments = true
normalize_doc_attributes = true

# Functions
fn_params_layout = "Tall"
fn_single_line = false

# Control flow
control_brace_style = "AlwaysSameLine"
force_multiline_blocks = false

# Misc
use_field_init_shorthand = true
use_try_shorthand = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Lower"
